"""Domain package exports."""

from backend.domain.edition import Claim, ReportEdition, SectionImpact
from backend.domain.blueprint import ChapterBlueprint, ReportBlueprint, SubsectionBlueprint
from backend.domain.chapter import (
    Chapter,
    ChapterDraft,
    DraftParagraph,
    SubsectionDraft,
    VisualIntent,
)
from backend.domain.enums import (
    ClaimRelation,
    EditionStatus,
    EvidenceType,
    ImpactDecision,
    IssueSeverity,
    MetricCategory,
    MetricDirection,
    PageType,
    ProjectStage,
    ReviewDecision,
    SourceRole,
    SourceStatus,
    VerificationStatus,
    VisualRole,
    VisualType,
)
from backend.domain.evidence import (
    ArchitectureFact,
    ContentBlock,
    EvidenceItem,
    EvidencePack,
    MetricFact,
    ProcessFact,
)
from backend.domain.project import CorpusSnapshot, Project, Source, SourcePage
from backend.domain.publication import (
    ExecutiveSummary,
    KeyResult,
    PublicationChapter,
    PublicationDocument,
    PublicationFigure,
    PublicationTable,
    ReferenceEntry,
)
from backend.domain.report_plan import (
    CorpusAnalysis,
    OutlineNode,
    QuantitativeFinding,
    ReportPlan,
)
from backend.domain.review import (
    EditorialReview,
    ReviewIssue,
    RevisionResult,
    TechnicalReview,
)
from backend.domain.section import Section, SectionVersion
from backend.domain.strategy import EvidenceTheme, ReportStrategy, TitleCandidate
from backend.domain.visual import VisualRequest

__all__ = [
    "ArchitectureFact",
    "Chapter",
    "ChapterBlueprint",
    "ChapterDraft",
    "Claim",
    "ClaimRelation",
    "ContentBlock",
    "CorpusAnalysis",
    "DraftParagraph",
    "EvidenceTheme",
    "CorpusSnapshot",
    "EditorialReview",
    "EditionStatus",
    "ExecutiveSummary",
    "EvidenceItem",
    "EvidencePack",
    "EvidenceType",
    "ImpactDecision",
    "IssueSeverity",
    "KeyResult",
    "MetricCategory",
    "MetricDirection",
    "MetricFact",
    "OutlineNode",
    "QuantitativeFinding",
    "PageType",
    "ProcessFact",
    "Project",
    "ProjectStage",
    "PublicationChapter",
    "PublicationDocument",
    "PublicationFigure",
    "PublicationTable",
    "ReportEdition",
    "ReportBlueprint",
    "ReportPlan",
    "ReportStrategy",
    "ReferenceEntry",
    "ReviewDecision",
    "ReviewIssue",
    "RevisionResult",
    "Section",
    "SectionImpact",
    "SectionVersion",
    "Source",
    "SourcePage",
    "SourceRole",
    "SourceStatus",
    "SubsectionBlueprint",
    "SubsectionDraft",
    "TechnicalReview",
    "TitleCandidate",
    "VerificationStatus",
    "VisualIntent",
    "VisualRole",
    "VisualRequest",
    "VisualType",
]
